plugins {
    id 'dev.architectury.loom' version '1.7-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4.162'
    id 'com.github.johnrengelman.shadow' version '8.1.1' apply false
    id 'org.jetbrains.kotlin.jvm' version '1.9.24' apply false
}

architectury {
    minecraft = project.minecraft_version
}

allprojects {
    version = rootProject.mod_version
    group = rootProject.maven_group
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'

    base {
        archivesName = "justarod-${project.name}"
    }

    repositories {
        maven { url = rootProject.uri('local-maven') }
        mavenCentral()
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.architectury.dev/' }
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://api.modrinth.com/maven' }
        maven { url = 'https://maven.terraformersmc.com/releases/' }
        maven {
            url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
            content {
                includeGroup 'software.bernie.geckolib'
                includeGroup 'com.eliotlash.mclib'
            }
        }
        maven { url = 'https://oss.sonatype.org/content/groups/public/' }
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        mappings "net.fabricmc:yarn:${rootProject.yarn_mappings}:v2"
    }

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(17)
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.release = 17
        options.encoding = 'UTF-8'
    }
}
